apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
        - name: syedimranullah7/ansible-pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80

    