apiVersion: apps/v1
kind: Service
metadata:
  name: devops-project-service
  labels:
    app: devops-project
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: devops-project
  type: Loadbalancer
  